/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import Accordion from "../components/Accordion";
import Form from "../components/Form";
import StudentsCards from "../components/StudentsCards";
import onlineClass from "../public/onlineClass.png";
import { FcNext } from "react-icons/fc";
import { AiOutlineDownCircle, AiOutlineCheckCircle } from "react-icons/ai";
import NavBar from "../components/NavBar";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Official Page</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="./Icon.png" />
			</Head>
			<section className="big-screen">
				<div className="section1">
					<div>
						<h1>
							Estas a <br />
							un paso de
							<br />
							<span>
								Cumplir <br />{" "}
								tus sueños
							</span>
						</h1>
					</div>
				</div>
				<div id="form" className="sectionForm">
					<Form />
				</div>
			</section>
			<div className="section3">
				<h2>¿Como funciona Learn English Together?</h2>
				<p>
					¡Es muy fácil! Tienes las clases
					disponibles para verlas a{" "}
					<span>cualquier hora del día</span> y
					desde cualquier lugar del mundo, abre la
					aplicación en tu computadora o celular y
					empieza a aprender. Nuestros profesores
					te harán seguimiento y de acuerdo a tu
					desempeño en las clases se pondrán en
					contacto contigo para agendar{" "}
					<span>
						clases en vivo personalizadas
					</span>{" "}
					con la finalidad de practicar y reforzar
					tus conocimientos, gracias a este método
					que combina el aprendizaje gramatical y
					la práctica conseguirás{" "}
					<span>
						resultados increíbles en muy
						poco tiempo
					</span>{" "}
					de la mano de profesionales
				</p>
			</div>
			<div className="section4">
				<div className="cta">
					<h2>
						¡Pierde el miedo de{" "}
						<span>hablar inglés!</span>
					</h2>
					<a href="#form">
						Completa el Formulario{" "}
						<FcNext className="i" />
					</a>
				</div>
			</div>
			<div className="section5">
				<StudentsCards />
			</div>
			<div className="section4b">
				<div className="cta">
					<h2>
						¿Estas listo para{" "}
						<span>ser bilingüe?</span>
					</h2>
					<a href="#form">
						Completa el Formulario{" "}
						<FcNext className="i" />
					</a>
				</div>
			</div>
			<div className="section6">
				<div>
					<Image
						className="Image"
						src={onlineClass}
					/>
				</div>
				<div>
					<>
						<h3>Aprende desde casa</h3>
						<p>
							Olvídate del mal clima o
							de pasar horas en
							tráfico. Ponte tu ropa
							más cómoda y recibe
							clases desde casa.
						</p>
					</>
					<>
						<h3>En cualquier momento</h3>
						<p>
							¡Elige el horario que
							más te convenga!
							Nuestras clases están
							disponibles las 24 horas
							del día al igual que
							nuestros asesores.
						</p>
					</>
					<>
						<h3>De fácil acceso</h3>
						<p>
							¡Estudia desde donde
							quieras! Conéctate a
							internet con tu
							computadora o celular y
							aprende inglés donde
							quieras.
						</p>
					</>
				</div>
			</div>
			<div className="section7">
				<h2>
					¡Conoce los planes que se{" "}
					<span>adaptan</span> a tus{" "}
					<span>necesidades!</span>
				</h2>
				<div>
					<p>
						<AiOutlineDownCircle className="i" />
						Llena el formulario
					</p>
					<p>
						<AiOutlineDownCircle className="i" />
						Te contactamos y aclaras tus
						dudas
					</p>
					<p>
						<AiOutlineDownCircle className="i" />
						Elige el plan que mas te
						convenga
					</p>
					<p>
						<AiOutlineCheckCircle className="check" />
						¡Listo! Comienza a aprender.
					</p>
				</div>
			</div>
			<div className="section4b">
				<div className="cta">
					<h2>
						¡No esperes más y{" "}
						<span>
							mejora tu futuro ahora!
						</span>
					</h2>
					<a href="#form">
						Completa el Formulario{" "}
						<FcNext
							style={{
								fontSize: "1.5rem",
							}}
						/>
					</a>
				</div>
			</div>
			<div className="section2">
				<h2>¿Por que elegirnos?</h2>
				<Accordion />
			</div>
		</div>
	);
}
